# Blog settings
permalink: :title


# My variables
name: React.js 小书
description: React.js 小书是一个开源、免费、专业、简单的 React.js 在线教程
site_root: /books/react
static_path: http://huzidaha.github.io/react-naive-book
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: none

gems:
  - jekyll-sitemap
